# workflow for continuous training of the model
name: Continuous Training

# define the name for the runner
on:
  push:
    branches:
      - azure
  schedule:
    - cron: '0 0 1 * *'

# specify to run in the latest ubuntu
jobs:
  # define the job name
  build:
    # specify the type of runner
    runs-on: ubuntu-latest
    # define the steps to run
    steps:
      # checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # set up python  
      - name: Run python script
        env:
          # set the environment variables
          SECRET_KEY_BS_AZURE: ${{ secrets.SECRET_KEY_BS_AZURE }}
          SECRET_NAME_BS_AZURE: ${{ secrets.SECRET_NAME_BS_AZURE }}
        run: |
          # install requirements
          pip install -r requirements.txt
          # run the script
          python src/train.py
