# workflow for continuous training of the model
name: Continuous Training

# define the name for the runner
on:
  push:
    branches:
      - azure
  schedule:
    - cron: '0 0 1 * *'

# specify to run in the latest ubuntu
jobs:
  # define the job name
  build:
    # specify the type of runner
    runs-on: ubuntu-latest
    # define the steps to run
    steps:
      # checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # run the python script
      - name: Run python script
        env:
          # set the environment variables
          SECRET_KEY_BS_AZURE: ${{ secrets.SECRET_KEY_BS_AZURE }}
          SECRET_NAME_BS_AZURE: ${{ secrets.SECRET_NAME_BS_AZURE }}
        run: |
          # install requirements
          pip install -r requirements.txt
          # run the script
          python src/train.py

      # commit the changes
      - name: Commit files
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add .
            git commit -m "Continuos training"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            force: true
            repository: 'sebassaras02/Default_prediction'
            github_token: ${{ secrets.GITHUB_TOKEN }}  
            branch: azure     